// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ddBM2KKJ0OWoyGvwU6u70qy7qc_p7qo',
    appId: '1:37829564517:web:85b9d32a3000dfd22d8e8c',
    messagingSenderId: '37829564517',
    projectId: 'chatapp-5b553',
    authDomain: 'chatapp-5b553.firebaseapp.com',
    storageBucket: 'chatapp-5b553.appspot.com',
    measurementId: 'G-FJKM9PDTVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrrGucM45uFJ-UyfOHJ27EbxLLS55Oo1c',
    appId: '1:37829564517:android:7868a74730b46b5d2d8e8c',
    messagingSenderId: '37829564517',
    projectId: 'chatapp-5b553',
    storageBucket: 'chatapp-5b553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-1Dos5EEbvzyA-gfxcSizvWhrcX8kMDg',
    appId: '1:37829564517:ios:7b0ad05b17924a752d8e8c',
    messagingSenderId: '37829564517',
    projectId: 'chatapp-5b553',
    storageBucket: 'chatapp-5b553.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-1Dos5EEbvzyA-gfxcSizvWhrcX8kMDg',
    appId: '1:37829564517:ios:cd44d9cd7077c9842d8e8c',
    messagingSenderId: '37829564517',
    projectId: 'chatapp-5b553',
    storageBucket: 'chatapp-5b553.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
